### ISSUE TITLE
Set up kanban board.

### ISSUE THREAD

**Issue by Lordkaito** [Lordkaito/recipe-app#15]
Here we just created the kanban board for the project. 
Our team has two people, @leolpaz and @Lordkaito.
Here is the [link](https://github.com/Lordkaito/recipe-app/projects/1)

**Comment by elyor-doniyorov** [comment]
Hi @Lordkaito and @leolpaz, 

Your Kanban board is complete!  There is nothing else to say other than... you can start working on tasks :shipit: 
Congratulations! 🎉 

# STATUS APPROVED ✅ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
